"""restore_assistant_modules

Revision ID: 9d934dec52a6
Revises: 0001_echo_initial
Create Date: 2026-08-06 09:42:25.362617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d934dec52a6'
down_revision: Union[str, None] = '0001_echo_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('in_group_only', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_personas_is_active'), 'agent_personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_personas_user_id'), 'agent_personas', ['user_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=256), nullable=True),
    sa.Column('root_span_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cached_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_cny', sa.Float(), nullable=False),
    sa.Column('models_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loop_run_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_loop_run_id'), 'agent_traces', ['loop_run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_started_at'), 'agent_traces', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_traces_status'), 'agent_traces', ['status'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_id'), 'agent_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_type'), 'agent_traces', ['task_type'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_id'), 'agent_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_agent_traces_user_id'), 'agent_traces', ['user_id'], unique=False)
    op.create_index('ix_agent_traces_user_started', 'agent_traces', ['user_id', 'started_at'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_favorite')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('loop_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('verifier_model', sa.String(length=128), nullable=True),
    sa.Column('verifier_kind', sa.String(length=16), nullable=True),
    sa.Column('rubric_name', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loop_runs_status'), 'loop_runs', ['status'], unique=False)
    op.create_index(op.f('ix_loop_runs_task_id'), 'loop_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_loop_runs_task_type'), 'loop_runs', ['task_type'], unique=False)
    op.create_index(op.f('ix_loop_runs_user_id'), 'loop_runs', ['user_id'], unique=False)
    op.create_table('notify_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_channels_enabled'), 'notify_channels', ['enabled'], unique=False)
    op.create_index(op.f('ix_notify_channels_user_id'), 'notify_channels', ['user_id'], unique=False)
    op.create_table('persona_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('member_persona_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enable_tools', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_groups_user_id'), 'persona_groups', ['user_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_status'), 'research_reports', ['status'], unique=False)
    op.create_index(op.f('ix_research_reports_user_id'), 'research_reports', ['user_id'], unique=False)
    op.create_table('agent_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cny', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iteration_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_spans_iteration_id'), 'agent_spans', ['iteration_id'], unique=False)
    op.create_index(op.f('ix_agent_spans_parent_span_id'), 'agent_spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_agent_spans_span_id'), 'agent_spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_agent_spans_span_type'), 'agent_spans', ['span_type'], unique=False)
    op.create_index(op.f('ix_agent_spans_status'), 'agent_spans', ['status'], unique=False)
    op.create_index(op.f('ix_agent_spans_trace_id'), 'agent_spans', ['trace_id'], unique=False)
    op.create_index('ix_agent_spans_trace_started', 'agent_spans', ['trace_id', 'started_at'], unique=False)
    op.create_index('ix_agent_spans_type_status', 'agent_spans', ['span_type', 'status'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_group_members_conversation_id'), 'group_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('loop_iterations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('iteration_no', sa.Integer(), nullable=False),
    sa.Column('artifact_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('repair_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['loop_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loop_iterations_run_id'), 'loop_iterations', ['run_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tool_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_kb_id'), 'skills', ['kb_id'], unique=False)
    op.create_index(op.f('ix_skills_user_id'), 'skills', ['user_id'], unique=False)
    op.add_column('agent_configs', sa.Column('show_avatar', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('agent_configs', sa.Column('human_mode', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('conversations', sa.Column('is_group', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('conversations', sa.Column('member_persona_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('enable_tools', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('conversations', sa.Column('join_code', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_conversations_is_group'), 'conversations', ['is_group'], unique=False)
    op.create_index(op.f('ix_conversations_join_code'), 'conversations', ['join_code'], unique=False)
    op.add_column('messages', sa.Column('sender_persona_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('sender_user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_user_id')
    op.drop_column('messages', 'sender_persona_id')
    op.drop_index(op.f('ix_conversations_join_code'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_group'), table_name='conversations')
    op.drop_column('conversations', 'join_code')
    op.drop_column('conversations', 'enable_tools')
    op.drop_column('conversations', 'member_persona_ids')
    op.drop_column('conversations', 'is_group')
    op.drop_column('agent_configs', 'human_mode')
    op.drop_column('agent_configs', 'show_avatar')
    op.drop_index(op.f('ix_skills_user_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_kb_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_loop_iterations_run_id'), table_name='loop_iterations')
    op.drop_table('loop_iterations')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_conversation_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_agent_spans_type_status', table_name='agent_spans')
    op.drop_index('ix_agent_spans_trace_started', table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_trace_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_status'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_span_type'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_span_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_parent_span_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_iteration_id'), table_name='agent_spans')
    op.drop_table('agent_spans')
    op.drop_index(op.f('ix_research_reports_user_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_status'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_persona_groups_user_id'), table_name='persona_groups')
    op.drop_table('persona_groups')
    op.drop_index(op.f('ix_notify_channels_user_id'), table_name='notify_channels')
    op.drop_index(op.f('ix_notify_channels_enabled'), table_name='notify_channels')
    op.drop_table('notify_channels')
    op.drop_index(op.f('ix_loop_runs_user_id'), table_name='loop_runs')
    op.drop_index(op.f('ix_loop_runs_task_type'), table_name='loop_runs')
    op.drop_index(op.f('ix_loop_runs_task_id'), table_name='loop_runs')
    op.drop_index(op.f('ix_loop_runs_status'), table_name='loop_runs')
    op.drop_table('loop_runs')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_agent_traces_user_started', table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_user_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_trace_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_type'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_status'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_started_at'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_loop_run_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_agent_personas_user_id'), table_name='agent_personas')
    op.drop_index(op.f('ix_agent_personas_is_active'), table_name='agent_personas')
    op.drop_table('agent_personas')
    # ### end Alembic commands ###
