"""add_daily_reviews

Revision ID: 9e98715562bd
Revises: 9d934dec52a6
Create Date: 2026-08-08 11:03:37.304328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '9e98715562bd'
down_revision: Union[str, None] = '9d934dec52a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if 'daily_reviews' in inspect(op.get_bind()).get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('care', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_date', name='uq_daily_review')
    )
    op.create_index(op.f('ix_daily_reviews_review_date'), 'daily_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_daily_reviews_user_id'), 'daily_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reviews_user_id'), table_name='daily_reviews')
    op.drop_index(op.f('ix_daily_reviews_review_date'), table_name='daily_reviews')
    op.drop_table('daily_reviews')
    # ### end Alembic commands ###
